[package]
description = "Endpoint to expose Prometheus metrics"
name = "substrate-prometheus-endpoint"
version = "0.8.0-alpha.4"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[dependencies]
log = "0.4.8"
futures-util = { version = "0.3.1", default-features = false, features = ["io"] }
derive_more = "0.99"

# WASM
[target.'cfg(target_os = "unknown")'.dependencies]
prometheus = "0.7"

[target.'cfg(not(target_os = "unknown"))'.dependencies]
async-std = { version = "1.0.1", features = ["unstable"] }
hyper = { version = "0.13.1", default-features = false, features = ["stream"] }
prometheus = { version = "0.7", features = ["process"] }
tokio = "0.2"
